%% Meshing-Mapper release examples
% This script is the main user workspace. Each section defines a baseline,
% a labeled source, the labels to transfer, and the baseline labels where
% replacement is allowed. Mesh dimensions are expressed in centimeters.

close all;
clc;

repoRoot = fileparts(mfilename('fullpath'));
addpath(fullfile(repoRoot, 'Lib'));

exampleData = fullfile(repoRoot, 'examples', 'mapper', 'data');
exampleOutput = fullfile(repoRoot, 'examples', 'mapper', 'output');
if ~exist('figureVisibility', 'var')
    figureVisibility = 'on';
end

% Choose how the example inputs are obtained:
%   "load"     use the committed DAT/MSH files (fast, default)
%   "generate" recreate every DAT/MSH file from the geometry definitions
if ~exist('exampleDataMode', 'var')
    exampleDataMode = "load";
end
if ~exist('runOptimizationExamples', 'var')
    runOptimizationExamples = false;
end
if ~exist('runMexBuildExample', 'var')
    runMexBuildExample = false;
end
files = resolveExampleMeshes(exampleData, exampleDataMode);

%% DAT example 1: centered 3 cm sphere in a homogeneous 5 cm cube
baseline = files.BaselineDat;
sphereSource = files.SphereDat;

visualizeDatLabelGroups(baseline, {10}, ...
    'GroupNames', "homogeneous baseline", ...
    'Colors', [0.70 0.74 0.80], ...
    'Alphas', 0.22, ...
    'Visible', figureVisibility, ...
    'OutputFolder', exampleOutput, ...
    'OutputName', 'dat_1_starting_baseline', ...
    'Title', 'DAT example 1 - starting 5 cm baseline');
visualizeDatLabelGroups(sphereSource, {1}, ...
    'GroupNames', "3 cm sphere", ...
    'Colors', [0.90 0.25 0.20], ...
    'Alphas', 0.90, ...
    'Visible', figureVisibility, ...
    'OutputFolder', exampleOutput, ...
    'OutputName', 'dat_1_source_sphere', ...
    'Title', 'DAT example 1 - source sphere');

sphereSetup = struct();
sphereSetup.InputLabels = 1;
sphereSetup.NewLabels = 11;
sphereSetup.TargetLabels = 10;
sphereSetup.InputLabelNames = "sphere";
sphereSetup.NewLabelNames = "mapped_sphere";
sphereSetup.OutputFile = fullfile(exampleOutput, 'dat_1_sphere_remap.dat');
sphereSetup.LogFile = fullfile(exampleOutput, 'dat_1_sphere_remap_log.txt');
sphere_remap = remap(baseline, sphereSource, sphereSetup);

visualizeDatLabelGroups(sphere_remap.OutputFile, {10, 11}, ...
    'GroupNames', ["baseline", "mapped sphere"], ...
    'Colors', [0.70 0.74 0.80; 0.90 0.25 0.20], ...
    'Alphas', [0.16 0.90], ...
    'Visible', figureVisibility, ...
    'OutputFolder', exampleOutput, ...
    'OutputName', 'dat_1_remapped', ...
    'Title', 'DAT example 1 - remapped baseline');

%% DAT example 2: map all three source labels into both baseline layers
layeredBaseline = files.LayeredBaselineDat;
multiShapeSource = files.MultiShapeDat;

visualizeDatLabelGroups(layeredBaseline, {10, 20}, ...
    'GroupNames', ["outer 5 cm cube", "denser inner 4 cm cube"], ...
    'Colors', [0.65 0.70 0.78; 0.30 0.55 0.85], ...
    'Alphas', [0.12 0.25], ...
    'Visible', figureVisibility, ...
    'OutputFolder', exampleOutput, ...
    'OutputName', 'dat_2_starting_layered_baseline', ...
    'Title', 'DAT example 2 - two-layer baseline');
visualizeDatLabelGroups(multiShapeSource, {1, 2, 3}, ...
    'GroupNames', ["3 cm sphere", "1 cm sphere", "0.5 cm cube"], ...
    'Colors', [0.78 0.82 0.90; 0.15 0.65 0.30; 0.95 0.55 0.10], ...
    'Alphas', [0.20 0.95 0.95], ...
    'Visible', figureVisibility, ...
    'OutputFolder', exampleOutput, ...
    'OutputName', 'dat_2_source_multishape', ...
    'Title', 'DAT example 2 - three-label source');

allLabelsSetup = struct();
allLabelsSetup.InputLabels = [1 2 3];
allLabelsSetup.NewLabels = [31 32 33];
allLabelsSetup.TargetLabels = [10 20];
allLabelsSetup.InputLabelNames = ["large sphere", "small sphere", "small cube"];
allLabelsSetup.NewLabelNames = ["mapped large sphere", "mapped small sphere", ...
    "mapped small cube"];
allLabelsSetup.OutputFile = fullfile(exampleOutput, 'dat_2_all_labels_remap.dat');
allLabelsSetup.LogFile = fullfile(exampleOutput, 'dat_2_all_labels_remap_log.txt');
all_labels_remap = remap(layeredBaseline, multiShapeSource, allLabelsSetup);

visualizeDatLabelGroups(all_labels_remap.OutputFile, {10, 20, 31, 32, 33}, ...
    'GroupNames', ["outer baseline", "inner baseline", "large sphere", ...
    "small sphere", "small cube"], ...
    'Colors', [0.65 0.70 0.78; 0.30 0.55 0.85; 0.78 0.82 0.90; ...
    0.15 0.65 0.30; 0.95 0.55 0.10], ...
    'Alphas', [0.08 0.12 0.18 0.95 0.95], ...
    'Visible', figureVisibility, ...
    'OutputFolder', exampleOutput, ...
    'OutputName', 'dat_2_all_labels_remapped', ...
    'Title', 'DAT example 2 - all source labels mapped');

%% DAT example 3: map only internal source labels into inner baseline layer
internalOnlySetup = struct();
internalOnlySetup.InputLabels = [2 3];
internalOnlySetup.NewLabels = [32 33];
internalOnlySetup.TargetLabels = 20;
internalOnlySetup.InputLabelNames = ["small sphere", "small cube"];
internalOnlySetup.NewLabelNames = ["mapped small sphere", "mapped small cube"];
internalOnlySetup.OutputFile = fullfile(exampleOutput, ...
    'dat_3_internal_labels_inner_layer.dat');
internalOnlySetup.LogFile = fullfile(exampleOutput, ...
    'dat_3_internal_labels_inner_layer_log.txt');
internal_only_remap = remap(layeredBaseline, multiShapeSource, internalOnlySetup);

visualizeDatLabelGroups(internal_only_remap.OutputFile, {10, 20, 32, 33}, ...
    'GroupNames', ["outer baseline", "inner baseline", "small sphere", ...
    "small cube"], ...
    'Colors', [0.65 0.70 0.78; 0.30 0.55 0.85; ...
    0.15 0.65 0.30; 0.95 0.55 0.10], ...
    'Alphas', [0.08 0.16 0.95 0.95], ...
    'Visible', figureVisibility, ...
    'OutputFolder', exampleOutput, ...
    'OutputName', 'dat_3_internal_labels_remapped', ...
    'Title', 'DAT example 3 - internal labels mapped only to inner layer');

%% GiD MSH example 1: centered sphere in homogeneous cube
mshBaseline = files.BaselineMsh;
mshSphere = files.SphereMsh;

visualizeMshLabelGroups(mshBaseline, {10}, ...
    'GroupNames', "homogeneous baseline", ...
    'Colors', [0.70 0.74 0.80], ...
    'Alphas', 0.22, ...
    'Visible', figureVisibility, ...
    'OutputFolder', exampleOutput, ...
    'OutputName', 'msh_1_starting_baseline', ...
    'Title', 'MSH example 1 - starting 5 cm baseline');
visualizeMshLabelGroups(mshSphere, {1}, ...
    'GroupNames', "3 cm sphere", ...
    'Colors', [0.90 0.25 0.20], ...
    'Alphas', 0.90, ...
    'Visible', figureVisibility, ...
    'OutputFolder', exampleOutput, ...
    'OutputName', 'msh_1_source_sphere', ...
    'Title', 'MSH example 1 - source sphere');

mshSphereSetup = struct();
mshSphereSetup.InputLabels = 1;
mshSphereSetup.NewLabels = 11;
mshSphereSetup.TargetLabels = 10;
mshSphereSetup.OutputFile = fullfile(exampleOutput, 'msh_1_sphere_remap.msh');
msh_sphere_remap = remap(mshBaseline, mshSphere, mshSphereSetup);

visualizeMshLabelGroups(msh_sphere_remap.OutputFile, {10, 11}, ...
    'GroupNames', ["baseline", "mapped sphere"], ...
    'Colors', [0.70 0.74 0.80; 0.90 0.25 0.20], ...
    'Alphas', [0.16 0.90], ...
    'Visible', figureVisibility, ...
    'OutputFolder', exampleOutput, ...
    'OutputName', 'msh_1_remapped', ...
    'Title', 'MSH example 1 - remapped baseline');

%% GiD MSH example 2: selected internal labels into inner baseline layer
mshInternalSetup = struct();
mshInternalSetup.InputLabels = [2 3];
mshInternalSetup.NewLabels = [32 33];
mshInternalSetup.TargetLabels = 20;
mshInternalSetup.OutputFile = fullfile(exampleOutput, ...
    'msh_2_internal_labels_inner_layer.msh');
msh_internal_remap = remap(files.LayeredBaselineMsh, ...
    files.MultiShapeMsh, mshInternalSetup);

visualizeMshLabelGroups(files.MultiShapeMsh, {1, 2, 3}, ...
    'GroupNames', ["3 cm sphere", "1 cm sphere", "0.5 cm cube"], ...
    'Colors', [0.78 0.82 0.90; 0.15 0.65 0.30; 0.95 0.55 0.10], ...
    'Alphas', [0.20 0.95 0.95], ...
    'Visible', figureVisibility, ...
    'OutputFolder', exampleOutput, ...
    'OutputName', 'msh_2_source_multishape', ...
    'Title', 'MSH example 2 - three-label source');
visualizeMshLabelGroups(msh_internal_remap.OutputFile, {10, 20, 32, 33}, ...
    'GroupNames', ["outer baseline", "inner baseline", "small sphere", ...
    "small cube"], ...
    'Colors', [0.65 0.70 0.78; 0.30 0.55 0.85; ...
    0.15 0.65 0.30; 0.95 0.55 0.10], ...
    'Alphas', [0.08 0.16 0.95 0.95], ...
    'Visible', figureVisibility, ...
    'OutputFolder', exampleOutput, ...
    'OutputName', 'msh_2_internal_labels_remapped', ...
    'Title', 'MSH example 2 - selected labels mapped to inner layer');

%% DAT optimization examples: serial, parallel, and optional MEX
% Disabled by default. Set runOptimizationExamples=true before running
% main.m. These cases use the same sphere/baseline geometry and write
% separate outputs so their optimizationInfo structures can be compared.
if runOptimizationExamples
    serialSetup = sphereSetup;
    serialSetup.NewLabels = 41;
    serialSetup.NewLabelNames = "serial sphere";
    serialSetup.OutputFile = fullfile(exampleOutput, ...
        'dat_optimization_serial_matlab.dat');
    serialSetup.LogFile = fullfile(exampleOutput, ...
        'dat_optimization_serial_matlab_log.txt');
    serialSetup.UseParallel = false;
    serialSetup.UseMex = false;
    serial_result = remap(baseline, sphereSource, serialSetup);

    parallelSetup = sphereSetup;
    parallelSetup.NewLabels = 42;
    parallelSetup.NewLabelNames = "parallel sphere";
    parallelSetup.OutputFile = fullfile(exampleOutput, ...
        'dat_optimization_parallel_matlab.dat');
    parallelSetup.LogFile = fullfile(exampleOutput, ...
        'dat_optimization_parallel_matlab_log.txt');
    parallelSetup.UseParallel = true;
    parallelSetup.ParallelPoolType = "auto";
    parallelSetup.ParallelWorkers = 32;
    parallelSetup.ChunkSize = 500;
    parallelSetup.UseMex = false;
    parallel_result = remap(baseline, sphereSource, parallelSetup);

    mexSetup = sphereSetup;
    mexSetup.NewLabels = 43;
    mexSetup.NewLabelNames = "MEX-enabled sphere";
    mexSetup.OutputFile = fullfile(exampleOutput, ...
        'dat_optimization_mex.dat');
    mexSetup.LogFile = fullfile(exampleOutput, ...
        'dat_optimization_mex_log.txt');
    mexSetup.UseParallel = false;
    mexSetup.UseMex = true;
    mexSetup.BuildMex = false;
    mexSetup.MexRequired = false;
    mex_result = remap(baseline, sphereSource, mexSetup);

    if runMexBuildExample
        mexBuildSetup = mexSetup;
        mexBuildSetup.NewLabels = 44;
        mexBuildSetup.NewLabelNames = "compiled MEX sphere";
        mexBuildSetup.OutputFile = fullfile(exampleOutput, ...
            'dat_optimization_build_mex.dat');
        mexBuildSetup.LogFile = fullfile(exampleOutput, ...
            'dat_optimization_build_mex_log.txt');
        mexBuildSetup.BuildMex = true;
        mexBuildSetup.MexVerbose = false;
        mexBuildSetup.MexRequired = true;
        mex_build_result = remap(baseline, sphereSource, mexBuildSetup);
    end
end

fprintf('\nAll examples completed. Outputs: %s\n', exampleOutput);
