%TEST_MAPDATMESHLABELS Map input .dat material volumes onto an output .dat mesh.
clear;
close all;
clc;

inputDatFile = fullfile(pwd, 'Input_mesh.dat');
targetDatFile = fullfile(pwd, 'Output_mesh.dat');
newDatFile = fullfile(pwd, 'New_remap.dat');
logFile = fullfile(pwd, 'Output_mesh_mapped_input_label_log.txt');
validationPlotFolder = fullfile(pwd, 'validation_plots');
validationFigureVisibility = 'on';

% Select the target subdomains where the input volume is allowed to project.
% Use [] to search all target labels.
targetLabelsToProject = [1 2];
targetLabelNames = ["air"; "cylinder"];
inputLabelNames = "target";
newLabelNames = "target";

[mappedLabels, mapInfo] = mapDatMeshLabels( ...
    inputDatFile, targetDatFile, ...
    'TargetLabels', targetLabelsToProject, ...
    'TargetLabelNames', targetLabelNames, ...
    'InputLabelNames', inputLabelNames, ...
    'NewLabelNames', newLabelNames, ...
    'OutputDatFile', newDatFile, ...
    'LogFile', logFile);

fprintf('Input DAT mesh: %d nodes, %d tetrahedra\n', ...
    size(mapInfo.inputMesh.nodes, 1), size(mapInfo.inputMesh.elements, 1));
fprintf('Target DAT mesh: %d nodes, %d tetrahedra\n', ...
    size(mapInfo.targetMesh.nodes, 1), size(mapInfo.targetMesh.elements, 1));
fprintf('Target labels searched: %s\n', strjoin(compose('%g', mapInfo.targetLabelsToMap), ', '));
for row = 1:height(mapInfo.labelMap)
    fprintf('Input label %g (%s) -> output label %g (%s): %d target tetrahedra\n', ...
        mapInfo.labelMap.InputLabel(row), ...
        char(mapInfo.labelMap.InputLabelName(row)), ...
        mapInfo.labelMap.NewTargetLabel(row), ...
        char(mapInfo.labelMap.NewTargetLabelName(row)), ...
        mapInfo.labelMap.MappedTargetElements(row));
end
fprintf('Mapped DAT written to: %s\n', newDatFile);
fprintf('Label log written to: %s\n', logFile);
fprintf('Validation plots written to: %s\n', validationPlotFolder);

labelsToValidate = mapInfo.outputLabelTable.Label;
labelNamesToValidate = mapInfo.outputLabelTable.Name;
plotDatMaterialLabels( ...
    mapInfo.targetMesh, ...
    'ElementLabels', mappedLabels, ...
    'LabelsToPlot', labelsToValidate, ...
    'LabelNames', labelNamesToValidate, ...
    'PlotMode', 'separate', ...
    'SaveFolder', validationPlotFolder, ...
    'Visible', validationFigureVisibility);
