%TEST_TRANSFORMMESHGEOMETRY Build translated/rotated versions of the input mask.
%
% The input mask mesh is the geometry projected onto the output mesh. These
% examples modify only node coordinates: node count, element connectivity,
% and labels/materials are kept unchanged.

clear;
close all;
clc;

inputDatFile = fullfile(pwd, 'Input_mesh.dat');
targetDatFile = fullfile(pwd, 'Output_mesh.dat');
inputMshFile = fullfile(pwd, 'Mesh_elipse.msh');

translatedDatFile = fullfile(pwd, 'Input_mesh_translated.dat');
rotatedDatFile = fullfile(pwd, 'Input_mesh_rotated_z30.dat');
rotatedTranslatedDatFile = fullfile(pwd, 'Input_mesh_rotated_z30_translated.dat');
rotatedTranslatedMshFile = fullfile(pwd, 'Mesh_elipse_rotated_z30_translated.msh');
remappedDatFile = fullfile(pwd, 'New_remap_rotated_translated.dat');
remapLogFile = fullfile(pwd, 'New_remap_rotated_translated_label_log.txt');
plotFolder = fullfile(pwd, 'transform_validation_plots');

% Set to 'off' for fully hidden batch plots, or 'on' for interactive MATLAB.
figureVisibility = 'on';

fprintf('Case 1: translation only\n');
translationOnly = transformMeshGeometry( ...
    inputDatFile, ...
    translatedDatFile, ...
    'TranslationInitialPoint', [0 0 0], ...
    'TranslationFinalPoint', [1.00 -0.75 0.25], ...
    'TransformOrder', {'translation'});
printTransformSummary(translationOnly);

fprintf('\nCase 2: rotation only about the default z-axis\n');
rotationOnly = transformMeshGeometry( ...
    inputDatFile, ...
    rotatedDatFile, ...
    'RotationAngle', 30, ...
    'TransformOrder', {'rotation'});
printTransformSummary(rotationOnly);

fprintf('\nCase 3: rotate first, then translate the mask in x/y/z\n');
rotatedTranslated = transformMeshGeometry( ...
    inputDatFile, ...
    rotatedTranslatedDatFile, ...
    'RotationAxis', [0 0 1], ...
    'RotationAngle', 30, ...
    'TranslationInitialPoint', [0 0 0], ...
    'TranslationFinalPoint', [1.25 0.75 0.10], ...
    'TransformOrder', {'rotation', 'translation'});
printTransformSummary(rotatedTranslated);

fprintf('\nCase 4: same rotation/translation applied to the GiD .msh mask\n');
rotatedTranslatedMsh = transformMeshGeometry( ...
    inputMshFile, ...
    rotatedTranslatedMshFile, ...
    'RotationAxis', [0 0 1], ...
    'RotationAngle', 30, ...
    'TranslationInitialPoint', [0 0 0], ...
    'TranslationFinalPoint', [1.25 0.75 0.10], ...
    'TransformOrder', {'rotation', 'translation'});
printTransformSummary(rotatedTranslatedMsh);

fprintf('\nRemapping the rotated-translated DAT mask onto the output mesh\n');
[mappedLabels, mapInfo] = mapDatMeshLabels( ...
    rotatedTranslatedDatFile, ...
    targetDatFile, ...
    'TargetLabels', [1 2], ...
    'TargetLabelNames', ["air"; "cylinder"], ...
    'InputLabelNames', "target_rotated_translated", ...
    'NewLabelNames', "target_rotated_translated", ...
    'OutputDatFile', remappedDatFile, ...
    'LogFile', remapLogFile);

for row = 1:height(mapInfo.labelMap)
    fprintf('Input label %g (%s) -> output label %g (%s): %d target tetrahedra\n', ...
        mapInfo.labelMap.InputLabel(row), ...
        char(mapInfo.labelMap.InputLabelName(row)), ...
        mapInfo.labelMap.NewTargetLabel(row), ...
        char(mapInfo.labelMap.NewTargetLabelName(row)), ...
        mapInfo.labelMap.MappedTargetElements(row));
end

fprintf('\nPlotting the transformed input mask and final remapped labels\n');
plotDatMaterialLabels( ...
    rotatedTranslatedDatFile, ...
    'LabelsToPlot', 1, ...
    'LabelNames', "rotated_translated_input", ...
    'PlotMode', 'separate', ...
    'SaveFolder', plotFolder, ...
    'Visible', figureVisibility);

plotDatMaterialLabels( ...
    mapInfo.targetMesh, ...
    'ElementLabels', mappedLabels, ...
    'LabelsToPlot', mapInfo.outputLabelTable.Label, ...
    'LabelNames', mapInfo.outputLabelTable.Name, ...
    'PlotMode', 'separate', ...
    'SaveFolder', plotFolder, ...
    'Visible', figureVisibility);

fprintf('Transformed DAT files:\n');
fprintf('  %s\n', translatedDatFile);
fprintf('  %s\n', rotatedDatFile);
fprintf('  %s\n', rotatedTranslatedDatFile);
fprintf('Transformed MSH file:\n');
fprintf('  %s\n', rotatedTranslatedMshFile);
fprintf('Remapped DAT file:\n');
fprintf('  %s\n', remappedDatFile);
fprintf('Transform validation plots:\n');
fprintf('  %s\n', plotFolder);

function printTransformSummary(info)
fprintf('  Output: %s\n', info.outputMeshFile);
fprintf('  Format: %s, nodes: %d, elements: %d\n', ...
    info.meshFormat, info.numberOfNodes, info.numberOfElements);
fprintf('  Translation vector: [%g %g %g]\n', info.translationVector);
fprintf('  Rotation axis: [%g %g %g], angle: %g %s\n', ...
    info.rotationAxis, info.rotationAngle, info.angleUnit);
fprintf('  Original bbox min/max:\n');
fprintf('    min [%g %g %g]\n', info.originalBoundingBox(1, :));
fprintf('    max [%g %g %g]\n', info.originalBoundingBox(2, :));
fprintf('  Transformed bbox min/max:\n');
fprintf('    min [%g %g %g]\n', info.transformedBoundingBox(1, :));
fprintf('    max [%g %g %g]\n', info.transformedBoundingBox(2, :));
end
