%VISUALIZE_BASE_FINER_SKIN_ANTENNAS Plot SKIN against antenna labels.
%
% This validation view uses the base/finer remapped DAT generated by
% build_head_mapping_base_finer. SKIN is plotted as label 28, while labels
% 3 through 18 are grouped into a single transparent "Antennas" entry.

clear;
close all;
clc;

repoRoot = getRepoRoot();
addpath(fullfile(repoRoot, 'Lib'));

resultDir = fullfile(repoRoot, 'result', 'base_finer');
datFile = fullfile(resultDir, 'mesh_base_with_head_finer.dat');

if exist(datFile, 'file') ~= 2
    error('visualizeBaseFinerSkinAntennas:MissingDat', ...
        'Run build_head_mapping_base_finer first to create %s.', datFile);
end

outputFormats = ["png", "fig"];
labelGroups = {28, 3:18};
legendNames = ["SKIN", "Antennas"];
groupColors = [ ...
    1.00 0.00 0.78; ...
    0.48 0.53 0.57];
groupAlphas = [0.82; 0.18];

visualizeDatLabelGroups( ...
    datFile, ...
    labelGroups, ...
    'GroupNames', legendNames, ...
    'Colors', groupColors, ...
    'Alphas', groupAlphas, ...
    'OutputFolder', resultDir, ...
    'OutputName', 'skin28_antennas3_18', ...
    'OutputFormats', outputFormats, ...
    'Title', 'Base/finer SKIN with antenna labels 3-18');

fprintf('Saved SKIN/antenna validation outputs in:\n  %s\n', resultDir);

function repoRoot = getRepoRoot()
scriptPath = mfilename('fullpath');
if isempty(scriptPath)
    repoRoot = pwd;
else
    repoRoot = fileparts(scriptPath);
end
end
