function figureHandles = plotDatLabels(datFile, labelsOrNames, varargin)
%PLOTDATLABELS Auxiliary plotter for labels in a custom problem-type .dat file.
%
%   plotDatLabels(datFile) plots every material label in the .dat file.
%
%   plotDatLabels(datFile, [1 3]) plots material labels 1 and 3.
%
%   plotDatLabels(datFile, ["air" "target"], 'LogFile', logFile) plots
%   labels by material name. Names are read from a remap log generated by
%   mapDatMeshLabels.
%
%   Name-value options:
%       'LogFile'      Remap log containing the "Output material labels"
%                      table. If omitted, the function tries to find a
%                      matching *_label_log.txt file next to datFile.
%       'PlotMode'     'separate' or 'overlay'. Default: 'separate'.
%       'SaveFolder'   Optional folder where PNG plots are saved.
%       'Visible'      Figure visibility: 'on' or 'off'. Default: 'on'.
%       'ShowContext'  Plot the whole mesh as a transparent context.
%                      Default: true.

if nargin < 2
    labelsOrNames = [];
end

parser = inputParser;
parser.FunctionName = mfilename;
addRequired(parser, 'datFile', @isTextScalar);
addRequired(parser, 'labelsOrNames', @(x) isempty(x) || isnumeric(x) || islogical(x) || isTextVector(x));
addParameter(parser, 'LogFile', '', @isTextScalar);
addParameter(parser, 'PlotMode', 'separate', @isTextScalar);
addParameter(parser, 'SaveFolder', '', @isTextScalar);
addParameter(parser, 'Visible', 'on', @isTextScalar);
addParameter(parser, 'ShowContext', true, @(x) islogical(x) && isscalar(x));
parse(parser, datFile, labelsOrNames, varargin{:});

datFile = char(parser.Results.datFile);
logFile = char(parser.Results.LogFile);
if isempty(logFile)
    logFile = findDefaultLogFile(datFile);
end

labelTable = table();
if ~isempty(logFile)
    labelTable = readLabelTableFromLog(logFile);
end

[labelsToPlot, labelNames] = resolveLabelRequest(parser.Results.labelsOrNames, labelTable);

if isempty(labelsToPlot)
    figureHandles = plotDatMaterialLabels( ...
        datFile, ...
        'PlotMode', parser.Results.PlotMode, ...
        'SaveFolder', parser.Results.SaveFolder, ...
        'Visible', parser.Results.Visible, ...
        'ShowContext', parser.Results.ShowContext);
else
    figureHandles = plotDatMaterialLabels( ...
        datFile, ...
        'LabelsToPlot', labelsToPlot, ...
        'LabelNames', labelNames, ...
        'PlotMode', parser.Results.PlotMode, ...
        'SaveFolder', parser.Results.SaveFolder, ...
        'Visible', parser.Results.Visible, ...
        'ShowContext', parser.Results.ShowContext);
end
end

function [labelsToPlot, labelNames] = resolveLabelRequest(labelsOrNames, labelTable)
labelsToPlot = [];
labelNames = strings(0, 1);

if isempty(labelsOrNames)
    if ~isempty(labelTable)
        labelsToPlot = labelTable.Label;
        labelNames = labelTable.Name;
    end
    return;
end

if isnumeric(labelsOrNames) || islogical(labelsOrNames)
    labelsToPlot = double(labelsOrNames(:));
    labelNames = namesForLabels(labelsToPlot, labelTable);
    return;
end

requestedNames = textColumn(labelsOrNames);
if isscalar(requestedNames) && strcmpi(requestedNames(1), "all")
    if isempty(labelTable)
        return;
    end
    labelsToPlot = labelTable.Label;
    labelNames = labelTable.Name;
    return;
end

if isempty(labelTable)
    error('plotDatLabels:MissingLabelLog', ...
        'A LogFile is required when plotting labels by name.');
end

labelsToPlot = zeros(numel(requestedNames), 1);
labelNames = strings(numel(requestedNames), 1);
for requestIndex = 1:numel(requestedNames)
    labelName = requestedNames(requestIndex);
    tableIndex = find(strcmpi(labelTable.Name, labelName), 1, 'first');
    if isempty(tableIndex)
        numericLabel = str2double(labelName);
        if ~isnan(numericLabel)
            tableIndex = find(labelTable.Label == numericLabel, 1, 'first');
        end
    end

    if isempty(tableIndex)
        error('plotDatLabels:UnknownLabelName', ...
            'Label name "%s" was not found in the log.', char(labelName));
    end

    labelsToPlot(requestIndex) = labelTable.Label(tableIndex);
    labelNames(requestIndex) = labelTable.Name(tableIndex);
end
end

function labelNames = namesForLabels(labelsToPlot, labelTable)
labelNames = strings(numel(labelsToPlot), 1);
for labelIndex = 1:numel(labelsToPlot)
    label = labelsToPlot(labelIndex);
    tableIndex = [];
    if ~isempty(labelTable)
        tableIndex = find(labelTable.Label == label, 1, 'first');
    end

    if isempty(tableIndex)
        labelNames(labelIndex) = sprintf('label_%.15g', label);
    else
        labelNames(labelIndex) = labelTable.Name(tableIndex);
    end
end
end

function logFile = findDefaultLogFile(datFile)
logFile = '';
[folder, name] = fileparts(datFile);
candidate = fullfile(folder, [name '_label_log.txt']);
if exist(candidate, 'file') == 2
    logFile = candidate;
    return;
end

matches = dir(fullfile(folder, '*_label_log.txt'));
for matchIndex = 1:numel(matches)
    candidate = fullfile(matches(matchIndex).folder, matches(matchIndex).name);
    if logReferencesDatFile(candidate, datFile)
        logFile = candidate;
        return;
    end
end
end

function tf = logReferencesDatFile(logFile, datFile)
tf = false;
rawLines = readTextLines(logFile);
datFile = normalizePath(datFile);
for lineIndex = 1:numel(rawLines)
    line = strtrim(rawLines{lineIndex});
    if startsWith(line, 'Output DAT:', 'IgnoreCase', true)
        loggedFile = strtrim(extractAfter(string(line), 'Output DAT:'));
        tf = strcmpi(normalizePath(char(loggedFile)), datFile);
        return;
    end
end
end

function labelTable = readLabelTableFromLog(logFile)
rawLines = readTextLines(logFile);
startLine = find(strcmpi(strtrim(rawLines), 'Output material labels'), 1, 'first');
if isempty(startLine)
    error('plotDatLabels:MissingLabelTable', ...
        'Could not find "Output material labels" in %s.', logFile);
end

labels = zeros(0, 1);
names = strings(0, 1);
cursor = startLine + 2;
while cursor <= numel(rawLines)
    line = strtrim(rawLines{cursor});
    if isempty(line)
        break;
    end

    pieces = split(string(line), '|');
    if numel(pieces) < 2
        break;
    end

    label = str2double(strtrim(pieces(1)));
    if isnan(label)
        break;
    end

    labels(end + 1, 1) = label; %#ok<AGROW>
    names(end + 1, 1) = strtrim(pieces(2)); %#ok<AGROW>
    cursor = cursor + 1;
end

labelTable = table(labels, names, 'VariableNames', {'Label', 'Name'});
end

function rawLines = readTextLines(fileName)
fid = fopen(fileName, 'r');
if fid < 0
    error('plotDatLabels:OpenFailed', 'Could not open file: %s', fileName);
end
cleanup = onCleanup(@() fclose(fid));

rawLines = {};
line = fgetl(fid);
while ischar(line)
    rawLines{end + 1, 1} = line; %#ok<AGROW>
    line = fgetl(fid);
end
end

function normalized = normalizePath(fileName)
normalized = char(java.io.File(fileName).getCanonicalPath());
end

function names = textColumn(names)
if isempty(names)
    names = strings(0, 1);
elseif ischar(names)
    names = string({names});
elseif iscell(names)
    names = string(names(:));
else
    names = string(names(:));
end
names = strtrim(names);
end

function tf = isTextScalar(value)
tf = (ischar(value) && (isrow(value) || isempty(value))) || ...
     (isstring(value) && isscalar(value));
end

function tf = isTextVector(value)
tf = isempty(value) || ischar(value) || isstring(value) || iscellstr(value);
end
